"""initial schema with indexes and constraints

Revision ID: 3056895ce7cd
Revises: 
Create Date: 2026-09-02 14:03:39.276602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3056895ce7cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('track_type', sa.Enum('high_speed', 'technical', 'mixed', name='tracktype'), nullable=False),
    sa.Column('avg_overtaking_index', sa.Float(), nullable=True),
    sa.Column('avg_winner_grid_position', sa.Float(), nullable=True),
    sa.Column('avg_safety_cars', sa.Float(), nullable=True),
    sa.Column('avg_dnf_rate', sa.Float(), nullable=True),
    sa.Column('historical_rain_frequency', sa.Float(), nullable=True),
    sa.Column('avg_tire_degradation', sa.Float(), nullable=True),
    sa.Column('temperature_sensitivity', sa.Float(), nullable=True),
    sa.Column('lap_length_km', sa.Float(), nullable=True),
    sa.Column('total_laps', sa.Integer(), nullable=True),
    sa.Column('drs_zones', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_circuits_name')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('current_elo', sa.Float(), nullable=False),
    sa.Column('reliability_index', sa.Float(), nullable=True),
    sa.Column('avg_pit_stop_time', sa.Float(), nullable=True),
    sa.Column('strategic_error_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('aggressiveness_level', sa.Enum('conservative', 'balanced', 'aggressive', 'ultra_aggressive', name='aggressivenesslevel'), nullable=False),
    sa.Column('total_bets', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('current_elo', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_drivers_team_id', 'drivers', ['team_id'], unique=False)
    op.create_table('races',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('circuit_id', sa.UUID(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(length=255), nullable=False),
    sa.Column('race_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('qualifying_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sprint_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sprint_weekend', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'qualifying_done', 'finished', 'cancelled', name='racestatus'), nullable=False),
    sa.Column('deadline_bets', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'round_number', name='uq_races_season_round')
    )
    op.create_index('ix_races_circuit_id', 'races', ['circuit_id'], unique=False)
    op.create_index(op.f('ix_races_season'), 'races', ['season'], unique=False)
    op.create_index('ix_races_season_round', 'races', ['season', 'round_number'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('strategy_type', sa.Enum('conservative', 'balanced', 'aggressive', 'ultra_aggressive', name='strategytype'), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('allocations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_points', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'scored', 'void', name='betstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'race_id', name='uq_bets_user_race')
    )
    op.create_index('ix_bets_race_id', 'bets', ['race_id'], unique=False)
    op.create_index('ix_bets_user_id', 'bets', ['user_id'], unique=False)
    op.create_table('elo_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('driver', 'team', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('elo_before', sa.Float(), nullable=False),
    sa.Column('elo_after', sa.Float(), nullable=False),
    sa.Column('elo_delta', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'race_id', name='uq_elo_history_entity_race')
    )
    op.create_index(op.f('ix_elo_history_entity_id'), 'elo_history', ['entity_id'], unique=False)
    op.create_index('ix_elo_history_race_id', 'elo_history', ['race_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('top3_probability', sa.Float(), nullable=False),
    sa.Column('top10_probability', sa.Float(), nullable=False),
    sa.Column('dnf_probability', sa.Float(), nullable=False),
    sa.Column('expected_points', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('recommended_tokens', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_driver_id', 'predictions', ['driver_id'], unique=False)
    op.create_index('ix_predictions_race_id', 'predictions', ['race_id'], unique=False)
    op.create_table('qualifying_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('grid_position', sa.Integer(), nullable=False),
    sa.Column('q1_time', sa.Float(), nullable=True),
    sa.Column('q2_time', sa.Float(), nullable=True),
    sa.Column('q3_time', sa.Float(), nullable=True),
    sa.Column('gap_to_pole', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_qualifying_results_race_driver')
    )
    op.create_index('ix_qualifying_results_driver_id', 'qualifying_results', ['driver_id'], unique=False)
    op.create_index('ix_qualifying_results_race_id', 'qualifying_results', ['race_id'], unique=False)
    op.create_table('race_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('final_position', sa.Integer(), nullable=True),
    sa.Column('grid_position', sa.Integer(), nullable=False),
    sa.Column('points_scored', sa.Float(), nullable=False),
    sa.Column('fastest_lap', sa.Boolean(), nullable=False),
    sa.Column('dnf', sa.Boolean(), nullable=False),
    sa.Column('dnf_reason', sa.String(length=255), nullable=True),
    sa.Column('pit_stops', sa.Integer(), nullable=False),
    sa.Column('total_time', sa.Float(), nullable=True),
    sa.Column('laps_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_race_results_race_driver')
    )
    op.create_index('ix_race_results_driver_id', 'race_results', ['driver_id'], unique=False)
    op.create_index('ix_race_results_race_id', 'race_results', ['race_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('n_simulations', sa.Integer(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simulations_race_id', 'simulations', ['race_id'], unique=False)
    op.create_table('sprint_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('final_position', sa.Integer(), nullable=True),
    sa.Column('grid_position', sa.Integer(), nullable=False),
    sa.Column('points_scored', sa.Float(), nullable=False),
    sa.Column('dnf', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'driver_id', name='uq_sprint_results_race_driver')
    )
    op.create_index('ix_sprint_results_driver_id', 'sprint_results', ['driver_id'], unique=False)
    op.create_index('ix_sprint_results_race_id', 'sprint_results', ['race_id'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rain_probability', sa.Float(), nullable=False),
    sa.Column('rain_volume_mm', sa.Float(), nullable=False),
    sa.Column('temperature_air', sa.Float(), nullable=False),
    sa.Column('temperature_track_estimated', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=False),
    sa.Column('weather_risk_index', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('openweather', 'manual', 'historical', name='weathersource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_race_id', 'weather', ['race_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_race_id', table_name='weather')
    op.drop_table('weather')
    op.drop_index('ix_sprint_results_race_id', table_name='sprint_results')
    op.drop_index('ix_sprint_results_driver_id', table_name='sprint_results')
    op.drop_table('sprint_results')
    op.drop_index('ix_simulations_race_id', table_name='simulations')
    op.drop_table('simulations')
    op.drop_index('ix_race_results_race_id', table_name='race_results')
    op.drop_index('ix_race_results_driver_id', table_name='race_results')
    op.drop_table('race_results')
    op.drop_index('ix_qualifying_results_race_id', table_name='qualifying_results')
    op.drop_index('ix_qualifying_results_driver_id', table_name='qualifying_results')
    op.drop_table('qualifying_results')
    op.drop_index('ix_predictions_race_id', table_name='predictions')
    op.drop_index('ix_predictions_driver_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_elo_history_race_id', table_name='elo_history')
    op.drop_index(op.f('ix_elo_history_entity_id'), table_name='elo_history')
    op.drop_table('elo_history')
    op.drop_index('ix_bets_user_id', table_name='bets')
    op.drop_index('ix_bets_race_id', table_name='bets')
    op.drop_table('bets')
    op.drop_index('ix_races_season_round', table_name='races')
    op.drop_index(op.f('ix_races_season'), table_name='races')
    op.drop_index('ix_races_circuit_id', table_name='races')
    op.drop_table('races')
    op.drop_index('ix_drivers_team_id', table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('circuits')
    # ### end Alembic commands ###

    # Alembic's autogenerated downgrade drops the tables but NOT the Postgres
    # ENUM types that create_table implicitly created, so a
    # downgrade-then-upgrade fails with "type ... already exists". Drop them
    # explicitly to keep the migration reversible.
    for enum_name in (
        'tracktype',
        'aggressivenesslevel',
        'racestatus',
        'strategytype',
        'betstatus',
        'entitytype',
        'weathersource',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
